name: CD PUBLISH IMAGE AND UPDATE DEV

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - name: Extract gradle proyect vesrion and name 
        run: |
          VERSION=$(jq -r '.version' package.json)
          PROJECT_NAME=$(jq -r '.name' package.json)

          echo $VERSION
          echo $PROJECT_NAME

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ secrets.GH_USER }} --password-stdin

      - name: build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args:
            VITE_AUTH0_USERNAME=${{ secrets.AUTH0_DOMAIN }}
            VITE_AUTH0_PASSWORD=${{ secrets.AUTH0_CLIENT }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/tps-ingenieria-de-sistemas/${{ env.PROJECT_NAME }}:${{ env.VERSION }}
            ghcr.io/tps-ingenieria-de-sistemas/${{ env.PROJECT_NAME }}:latest

      - name: connect-and-run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_URL }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
          script: |
            cd infra
            sudo docker compose pull ${{ env.PROJECT_NAME }}
            sudo -E docker compose up -d ${{ env.PROJECT_NAME }}
